### PR TITLE
fix(#157) Follow the general rules of the eslint. Use the same settings as in the EOC project.

### LINKED ISSUE #157: Follow the general rules of the eslint. Use the same settings as in the EOC project.
To maintain a consistent architecture across the board, I believe we need to adhere to a common set of rules. I propose transferring the rules from EOC to the current project.

https://github.com/objectionary/eoc/blob/master/eslint.config.js

### PR DESCRIPTION
**Pull request by skulidropek**
Close #157 

Align ESLint configs with EOC rules and add eslint-plugin-promise in both eo2js and eo2js-runtime (locks refreshed).
Fix ESLint issues across runtime and tests; minimal code touch where possible.
Document the bitwise-specific lint exception in eo2js-runtime/src/runtime/bytes-of.js.
Ran npm run test (includes ESLint and all Grunt/Mocha suites) to verify.

### CODE REVIEW

**Comment by skulidropek** [comment]
@maxonfjvipon

File: eo2js-runtime/src/objects/org/eolang/try.js [hunk 1]
```diff
@@ -11,11 +11,11 @@ const data = require('../../../runtime/data');
  * Try.
  * @return {Object} - Try object
  */
-const _try = function() {
```
Comment (maxonfjvipon) [inline eo2js-runtime/src/objects/org/eolang/try.js:14]: @skulidropek can't we leave `_try`?

File: eo2js-runtime/src/objects/org/eolang/txt/regex$pattern$match$matched-from-index.js [hunk 2]
```diff
@@ -25,26 +25,25 @@ const regex$pattern$match$matched_from_index = function() {
     const from = dataized(start, NUMBER)
     let current = 1
     let matched
-    let result = undefined
+    let result
     while ((matched = regex.exec(text)) !== null) {
-      if (current !== from) {
```
Comment (maxonfjvipon) [inline eo2js-runtime/src/objects/org/eolang/txt/regex$pattern$match$matched-from-index.js:30]: @skulidropek why? This change seems to be unnecessary

File: eo2js-runtime/src/objects/org/eolang/txt/sprintf.js [hunk 3]
```diff
@@ -35,19 +38,19 @@ const bytesToHex = function(bts) {
  * }}
  */
 const CONVERSION = {
-  's': function(obj) {
+  's'(obj) {
```
Comment (maxonfjvipon) [inline eo2js-runtime/src/objects/org/eolang/txt/sprintf.js:41]: @skulidropek looks ugly to me, maybe we can turn it off? Or this is how javascript should look in 2025?

File: eo2js-runtime/test/fake/org/eolang/false.js [hunk 4]
```diff
@@ -7,7 +7,7 @@
  * For more information please read README.md in test/fake folder
  * @return {Object} - Object
  */
-const _false = function() {
+const falseObject = function() {
```
Comment (maxonfjvipon) [inline eo2js-runtime/test/fake/org/eolang/false.js]: @skulidropek the same as with `_try`. In order to keep all EO object consistent, let's leave these objects with `_`. We also generate such keyword-objects to js in `to-js.xsl` with `_`.

File: eo2js/test/commands/transpile.test.js [hunk 5]
```diff
@@ -119,29 +121,28 @@ describe('transpile', function() {
    *  Prerequisites for Fix:
    *  - All skipped tests must pass with current EO version
    */
-  describe('transformation packs', async function() {
+  describe('transformation packs', () => {
     const packs = path.resolve(__dirname, '../resources/transpile/packs')
-    await Promise.all(fs.readdirSync(packs)
```
Comment (maxonfjvipon) [inline eo2js/test/commands/transpile.test.js:124]: @skulidropek why? You've made this change in one of the recent previous PRs

**Review by maxonfjvipon — COMMENTED** [review]
@skulidropek see below

File: eo2js-runtime/src/objects/org/eolang/try.js (hunk 1 above)
Comment (skulidropek) [reply eo2js-runtime/src/objects/org/eolang/try.js:14]: Because there's no such rule in EOС. 

Current typing of eslint says that we shouldn't write code like that.
```
Unexpected dangling '_' in '_try'.eslint[no-underscore-dangle](https://eslint.org/docs/latest/rules/no-underscore-dangle)
```

File: eo2js-runtime/src/objects/org/eolang/txt/sprintf.js (hunk 3 above)
Comment (skulidropek) [reply eo2js-runtime/src/objects/org/eolang/txt/sprintf.js:41]: This is our common standard with EOC. We can disable it, but it would be preferable to disable it in both projects to have a common codebase standard.

File: eo2js-runtime/test/fake/org/eolang/false.js (hunk 4 above)
Comment (skulidropek) [reply eo2js-runtime/test/fake/org/eolang/false.js]: > the same as with `_try`. In order to keep all EO object consistent, let's leave these objects with `_`. We also generate such keyword-objects to js in `to-js.xsl` with `_`.

Okay

File: eo2js-runtime/src/objects/org/eolang/txt/regex$pattern$match$matched-from-index.js (hunk 2 above)
Comment (skulidropek) [reply eo2js-runtime/src/objects/org/eolang/txt/regex$pattern$match$matched-from-index.js:30]: @maxonfjvipon 
```
Error: It's not necessary to initialize 'result' to undefined.eslint[no-undef-init](https://eslint.org/docs/latest/rules/no-undef-init)
Code:     let result = undefined
```

```
Error: Unexpected use of continue statement.eslint[no-continue](https://eslint.org/docs/latest/rules/no-continue)
Code:         continue
```

image

File: eo2js/test/commands/transpile.test.js (hunk 5 above)
Comment (skulidropek) [reply eo2js/test/commands/transpile.test.js:124]: I checked and yes, I made some stupid changes. I reverted and fixed only the errors.

**Comment by skulidropek** [comment]
@maxonfjvipon

File: eo2js/src/commands/transpile.js [hunk 6]
```diff
@@ -51,12 +51,12 @@ const makeDirIfNotExist = function(dir) {
...
   const metas = xmir.program.metas
   let res = false
-  if (metas != null) {
-    const metas = xmir.program.metas.meta
-    if (Array.isArray(metas)) {
-      res = metas.findIndex((meta) => meta.head === name) !== -1
-    } else if (typeof metas === 'object' && metas.hasOwnProperty('head')) {
-      res = metas.head === name
+  if (metas !== null && metas !== undefined) {
+    const metaNodes = xmir.program.metas.meta
```
Comment (maxonfjvipon) [inline eo2js/src/commands/transpile.js]: @skulidropek let's rename this `metaNodes` to just `nodes`

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]
@skulidropek just little fix and we're good to merge

**Comment by skulidropek** [comment]
@maxonfjvipon 
Check it out.

I'll also gradually close other issues in my free time.

**Review by maxonfjvipon — APPROVED** [review]
@skulidropek LGTM! Thanks

**Comment by maxonfjvipon** [comment]
@rultor merge
